### ISSUE TITLE
Can't run with Java 8

### ISSUE THREAD

**Issue by InsaneLegacy** [filfat/MineiaGo#10]
And latest bungee

**Comment by InsaneLegacy** [comment]
My host only support Java 8

**Comment by filfat** [comment]
I don’t have a whole lot of experience with java so forgive me if this is a trivial issue.

Currently I compile it and test against openjdk11. I’ll look into ways of supporting older hosts but any help here would be appreciated 👍

**Comment by InsaneLegacy** [comment]
I will look an help out

**Comment by filfat** [comment]
Should be fixed in a recent commit.
